### ISSUE TITLE
Koan Error unexpected keyword argument 'virt_pxe_boot'

### ISSUE THREAD

**Issue by hktrivedi** [cobbler/koan#7]
I am testing Automated Build using Koan and Cobbler on RHEL 7.1. I am facing a problem while building a virtual instance on ESXi using Koan. Following are some details about the setup I am using. All these are on the same RHEL 7.1 server.

Cobbler Version : 2.6.7 (Distro/Profile/System created through Cobbler Web GUI.)
Koan Version : 2.6.7 (I use koan command with Cobbler system name.)
Python Version : 2.7.5

I am facing an issue executing following command. Please see the logs below.

[root@cobbler2 ~]# koan --server=localhost --port=80 --system=minimal2 --virt --virt-type=vmware
- looking for Cobbler at http://localhost:80/cobbler_api
- reading URL: http://localhost/cblr/svc/op/ks/system/minimal2
install_tree: http://192.168.6.89/cblr/links/rhel7.1-x86_64
- ['virt-install', '--version']
1.1.0
- ['virt-install', '--os-variant', 'list']
WARNING  KVM acceleration not available, using 'qemu'
ERROR   
--name is required
--memory amount in MiB is required
--disk storage must be specified (override with --nodisks)
An install method must be specified
(--location URL, --cdrom CD/ISO, --pxe, --import, --boot hd|cdrom|...)
<type 'exceptions.TypeError'>
start_install() got an unexpected keyword argument 'virt_pxe_boot'
  File "/usr/lib/python2.7/site-packages/koan/app.py", line 274, in main
    k.run()
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 424, in run
    self.virt()
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 843, in virt
    return self.net_install(after_download)
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 670, in net_install
    after_download(self, profile_data)
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 841, in after_download
    self.virt_net_install(profile_data)
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 1513, in virt_net_install
    osimport          =  self.virtinstall_osimport,

[root@cobbler2 ~]#

This works perfectly fine with Koan Version 2.2.2 installed on another machine. See the logs below.

[root@CobblerServerG1 ~]# koan --server=192.168.6.89 --port=80 --system=minimal2 --virt --virt-type=vmware
- looking for Cobbler at http://192.168.6.89:80/cobbler_api
- reading URL: http://192.168.6.89/cblr/svc/op/ks/system/minimal2
install_tree: http://192.168.6.89/cblr/links/rhel7.1-x86_64
libvirtd (pid 3898) is running...
DEBUG: interface=ens192
DEBGUG: management=True
DEBUG:  interfacetype=
DEBUG: management=1
DEBUG: name=minimal2
DEBUG: ram=2048
- saving virt disk image as /vmfs/volumes/datastore1/minimal2/minimal2.vmdk
- saving vmx file as /var/lib/tftpboot/koan_vmware//minimal2.vmx
None
[root@CobblerServerG1 ~]#

I checked the difference in /usr/lib/python2.x/site-packages/koan/app.py file of 2 different koan versions and it seems that there is a new parameter added in the app.py of koan 2.6.7. See the screenshot below. Can someone please tell me how to fix this ? I would highly appreciate it.

Koan 2.6.7 params

DISPLAY_PARAMS = [
   "name",
   "distro","profile",
   "kickstart","ks_meta",
   "install_tree","kernel","initrd",
   "netboot_enabled",
   "kernel_options",
   "repos",
   "virt_ram",
   "virt_disk",
   "virt_disk_driver",
   "virt_type",
   "virt_path",
   "virt_auto_boot",
   "virt_pxe_boot",
]

Koan 2.2.2 params

DISPLAY_PARAMS = [
   "name",
   "distro","profile",
   "kickstart","ks_meta",
   "install_tree","kernel","initrd",
   "netboot_enabled",
   "kernel_options",
   "repos",
   "virt_ram",
   "virt_disk",
   "virt_disk_driver",
   "virt_type",
   "virt_path",
   "virt_auto_boot",
]

Thanks,
Hrishikesh

**Comment by opoplawski** [comment]
Fixed with https://github.com/cobbler/cobbler/pull/1399  I guess I need to patch 2.6.7.

**Comment by opoplawski** [comment]
New pull for 2.6: https://github.com/cobbler/cobbler/pull/1600
